{{- if eq .Values.gardener.seed.provider "kubevirt" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
provisioner: kubernetes.io/no-provisioner
{{- end }}
